data = {
    "category":{
        "@scheme":"http:\/\/www.douban.com\/2007#kind",
        "@term":"http:\/\/www.douban.com\/2007#movie"
    },
    "db:tag":[
        {
            "@count":1977,
            "@name":"渡边信一郎"
        },
        {
            "@count":1766,
            "@name":"动画"
        },
        {
            "@count":1191,
            "@name":"日本"
        },
        {
            "@count":1122,
            "@name":"cowboy"
        },
        {
            "@count":987,
            "@name":"日本动画"
        },
        {
            "@count":622,
            "@name":"动漫"
        },
        {
            "@count":523,
            "@name":"bebop"
        },
        {
            "@count":517,
            "@name":"科幻"
        }
    ],
    "title":{
        "$t":"Cowboy Bebop"
    },
    "author":[
        {
            "name":{
                "$t":"渡边信一郎"
            }
        }
    ],
    "summary":{
        "$t":"2071年，随着超光速航行技术的实现，人类得以在太阳系范围内方便的移动，但是由于设计上的失误，这种技术引发了月球的爆炸，无数的月球碎片被吸引向地球，造成了空前绝后的大灾难。存活下来的人类逃离地球，并开始在太阳系各地建立家园。由于这次灾难，国家政府等权利机构都极为不稳定、治安问题也成为了一个难题。有些组织开始允许个人抓捕通缉的罪犯并换取奖金，这就是“赏金猎人”。史派克和杰特是驾驶飞船BEBOP号在宇宙中以捉拿逃犯获取奖金为生的赏金猎人。两人在星际间的旅程中，结识了身负巨债、嗜财如命的美女菲和电脑神童艾德，并收养了拥有高智商的数据狗爱因。从此，四人一狗游荡在广阔之宇宙之中，在自己与他人的生活中经历著种种悲欢离合，也寻找著各自的过去。©豆瓣"
    },
    "link":[
        {
            "@rel":"self",
            "@href":"http:\/\/api.douban.com\/movie\/subject\/1424406"
        },
        {
            "@rel":"alternate",
            "@href":"http:\/\/movie.douban.com\/subject\/1424406\/"
        },
        {
            "@rel":"image",
            "@href":"http:\/\/img3.douban.com\/spic\/s2975009.jpg"
        }
    ],
    "db:attribute":[
        {
            "$t":"Cowboy Bebop",
            "@name":"title"
        },
        {
            "$t":"http:\/\/www.cowboybebop.org\/",
            "@name":"website"
        },
        {
            "$t":"日本",
            "@name":"country"
        },
        {
            "$t":"村井贞行",
            "@name":"writer"
        },
        {
            "$t":"信本敬子",
            "@name":"writer"
        },
        {
            "$t":"渡边信一郎",
            "@name":"writer"
        },
        {
            "$t":"渡边信一郎",
            "@name":"director"
        },
        {
            "$t":"26",
            "@name":"episodes"
        },
        {
            "$t":"2003-01-08",
            "@name":"pubdate"
        },
        {
            "$t":"赏金猎人",
            "@name":"aka"
        },
        {
            "$t":"宇宙牛仔",
            "@name":"aka"
        },
        {
            "$t":"http:\/\/www.imdb.com\/title\/tt0213338\/",
            "@name":"imdb"
        },
        {
            "@lang":"zh_CN",
            "$t":"星际牛仔",
            "@name":"aka"
        },
        {
            "$t":"法语",
            "@name":"language"
        },
        {
            "$t":"德语",
            "@name":"language"
        },
        {
            "$t":"意大利语",
            "@name":"language"
        },
        {
            "$t":"西班牙语",
            "@name":"language"
        },
        {
            "$t":"塔加路语",
            "@name":"language"
        },
        {
            "$t":"英语",
            "@name":"language"
        },
        {
            "$t":"日语",
            "@name":"language"
        },
        {
            "$t":"山寺宏一",
            "@name":"cast"
        },
        {
            "$t":"石塚运昇",
            "@name":"cast"
        },
        {
            "$t":"林原惠",
            "@name":"cast"
        }
    ],
    "id":{
        "$t":"http:\/\/api.douban.com\/movie\/subject\/1424406"
    },
    "gd:rating":{
        "@min":0,
        "@numRaters":8830,
        "@average":"9.4",
        "@max":10
    }
};

book = {
    "category":{
        "@scheme":"http:\/\/www.douban.com\/2007#kind",
        "@term":"http:\/\/www.douban.com\/2007#book"
    },
    "db:tag":[
        {
            "@count":73,
            "@name":"片山恭一"
        },
        {
            "@count":32,
            "@name":"日本文学"
        },
        {
            "@count":20,
            "@name":"小说"
        },
        {
            "@count":17,
            "@name":"日本"
        },
        {
            "@count":13,
            "@name":"日本小说"
        },
        {
            "@count":12,
            "@name":"倘若我在彼岸"
        },
        {
            "@count":10,
            "@name":"纯爱"
        },
        {
            "@count":9,
            "@name":"爱情"
        }
    ],
    "title":{
        "$t":"倘若我在彼岸-日本畅销爱情小说"
    },
    "author":[
        {
            "name":{
                "$t":"片山恭一"
            }
        }
    ],
    "summary":{
        "$t":"《倘若我在彼岸》由三个看似独立实则相通的凄美的爱情故事组成。主人公是老师，都喜欢某种运动，他们都曾亲身经历过或目睹过接近死神的一瞬间并从中感悟或懂得了生命中的某些东西。"
    },
    "link":[
        {
            "@rel":"self",
            "@href":"http:\/\/api.douban.com\/book\/subject\/2023013"
        },
        {
            "@rel":"alternate",
            "@href":"http:\/\/book.douban.com\/subject\/2023013\/"
        },
        {
            "@rel":"image",
            "@href":"http:\/\/img3.douban.com\/spic\/s2328836.jpg"
        }
    ],
    "db:attribute":[
        {
            "$t":"7543639130",
            "@name":"isbn10"
        },
        {
            "$t":"9787543639133",
            "@name":"isbn13"
        },
        {
            "$t":"倘若我在彼岸-日本畅销爱情小说",
            "@name":"title"
        },
        {
            "$t":"193",
            "@name":"pages"
        },
        {
            "$t":"片山恭一",
            "@name":"author"
        },
        {
            "$t":"14.0",
            "@name":"price"
        },
        {
            "$t":"青岛出版社",
            "@name":"publisher"
        },
        {
            "$t":"平装",
            "@name":"binding"
        },
        {
            "$t":"2007-01-01",
            "@name":"pubdate"
        }
    ],
    "id":{
        "$t":"http:\/\/api.douban.com\/book\/subject\/2023013"
    },
    "gd:rating":{
        "@min":0,
        "@numRaters":148,
        "@average":"7.3",
        "@max":10
    }
};

bookes = {
    "opensearch:totalResults":{
        "$t":"5137"
    },
    "opensearch:startIndex":{
        "$t":"1"
    },
    "opensearch:itemsPerPage":{
        "$t":"10"
    },
    "entry":[
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "title":{
                "$t":"We Ar"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/3120891"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/3120891\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s3621814.jpg"
                }
            ],
            "db:attribute":[],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/3120891"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":11,
                "@average":"8.5",
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "title":{
                "$t":"WAD"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/1880994"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/1880994\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s1933496.jpg"
                }
            ],
            "db:attribute":[],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/1880994"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":82,
                "@average":"8.9",
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "title":{
                "$t":"我们爱科学"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/1871676"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/1871676\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s2611641.jpg"
                }
            ],
            "db:attribute":[],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/1871676"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":69,
                "@average":"8.5",
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Yevgeny Zamyatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/2473872"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/2473872\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s3100800.jpg"
                }
            ],
            "db:attribute":[
                {
                    "$t":"0140185852",
                    "@name":"isbn10"
                },
                {
                    "$t":"9780140185850",
                    "@name":"isbn13"
                },
                {
                    "$t":"Yevgeny Zamyatin",
                    "@name":"author"
                },
                {
                    "$t":"USD 14.00",
                    "@name":"price"
                },
                {
                    "$t":"Penguin Twentieth Century Classics",
                    "@name":"publisher"
                },
                {
                    "$t":"1993-08-01",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/2473872"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":13,
                "@average":"8.2",
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Eugene Zamiatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/1799755"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/1799755\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/pics\/book-default-small.gif"
                }
            ],
            "db:attribute":[
                {
                    "$t":"0140167102",
                    "@name":"isbn10"
                },
                {
                    "$t":"9780140167108",
                    "@name":"isbn13"
                },
                {
                    "$t":"Eugene Zamiatin",
                    "@name":"author"
                },
                {
                    "$t":"USD 10.00",
                    "@name":"price"
                },
                {
                    "$t":"Penguin Books",
                    "@name":"publisher"
                },
                {
                    "$t":"1991-07",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/1799755"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":3,
                "@average":0,
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Yevgeny Zamyatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/3410295"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/3410295\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s3970783.jpg"
                }
            ],
            "db:attribute":[
                {
                    "$t":"0099511436",
                    "@name":"isbn10"
                },
                {
                    "$t":"9780099511434",
                    "@name":"isbn13"
                },
                {
                    "$t":"Yevgeny Zamyatin",
                    "@name":"author"
                },
                {
                    "$t":"65.0",
                    "@name":"price"
                },
                {
                    "$t":"Vintage Classics",
                    "@name":"publisher"
                },
                {
                    "$t":"Natasha Randall",
                    "@name":"translator"
                },
                {
                    "$t":"2007-12-31",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/3410295"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":0,
                "@average":0,
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Yevgeny Zamyatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/4769643"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/4769643\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/pics\/book-default-small.gif"
                }
            ],
            "db:attribute":[
                {
                    "$t":"1439507155",
                    "@name":"isbn10"
                },
                {
                    "$t":"9781439507155",
                    "@name":"isbn13"
                },
                {
                    "$t":"Yevgeny Zamyatin",
                    "@name":"author"
                },
                {
                    "$t":"USD 16.99",
                    "@name":"price"
                },
                {
                    "$t":"2008-06-26",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/4769643"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":0,
                "@average":0,
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Yevgeny Zamyatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/4024622"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/4024622\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s3970782.jpg"
                }
            ],
            "db:attribute":[
                {
                    "$t":"1442133406",
                    "@name":"isbn10"
                },
                {
                    "$t":"9781442133402",
                    "@name":"isbn13"
                },
                {
                    "$t":"Yevgeny Zamyatin",
                    "@name":"author"
                },
                {
                    "$t":"USD 14.95",
                    "@name":"price"
                },
                {
                    "$t":"CreateSpace",
                    "@name":"publisher"
                },
                {
                    "$t":"2009-04-09",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/4024622"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":0,
                "@average":0,
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Yevgeny Zamyatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/3302059"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/3302059\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/pics\/book-default-small.gif"
                }
            ],
            "db:attribute":[
                {
                    "$t":"0553125389",
                    "@name":"isbn10"
                },
                {
                    "$t":"9780553125382",
                    "@name":"isbn13"
                },
                {
                    "$t":"Yevgeny Zamyatin",
                    "@name":"author"
                },
                {
                    "$t":"Bantam Books",
                    "@name":"publisher"
                },
                {
                    "$t":"1978",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/3302059"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":0,
                "@average":0,
                "@max":10
            }
        },
        {
            "category":{
                "@scheme":"http:\/\/www.douban.com\/2007#kind",
                "@term":"http:\/\/www.douban.com\/2007#book"
            },
            "author":[
                {
                    "name":{
                        "$t":"Yevgeny Zamyatin"
                    }
                }
            ],
            "title":{
                "$t":"We"
            },
            "link":[
                {
                    "@rel":"self",
                    "@href":"http:\/\/api.douban.com\/book\/subject\/3301977"
                },
                {
                    "@rel":"alternate",
                    "@href":"http:\/\/book.douban.com\/subject\/3301977\/"
                },
                {
                    "@rel":"image",
                    "@href":"http:\/\/img3.douban.com\/spic\/s3364834.jpg"
                }
            ],
            "db:attribute":[
                {
                    "$t":"1843914468",
                    "@name":"isbn10"
                },
                {
                    "$t":"9781843914464",
                    "@name":"isbn13"
                },
                {
                    "$t":"Yevgeny Zamyatin",
                    "@name":"author"
                },
                {
                    "$t":"USD 16.95",
                    "@name":"price"
                },
                {
                    "$t":"Hesperus Press",
                    "@name":"publisher"
                },
                {
                    "$t":"Hugh Aplin",
                    "@name":"translator"
                },
                {
                    "$t":"2009-11-01",
                    "@name":"pubdate"
                }
            ],
            "id":{
                "$t":"http:\/\/api.douban.com\/book\/subject\/3301977"
            },
            "gd:rating":{
                "@min":0,
                "@numRaters":0,
                "@average":0,
                "@max":10
            }
        }
    ],
    "title":{
        "$t":"搜索 we 的结果"
    }
};

data = {
    "category":{
        "@scheme":"http:\/\/www.douban.com\/2007#kind",
        "@term":"http:\/\/www.douban.com\/2007#music"
    },
    "db:tag":[
        {
            "@count":255,
            "@name":"丁当"
        },
        {
            "@count":133,
            "@name":"台湾"
        },
        {
            "@count":79,
            "@name":"2011"
        },
        {
            "@count":56,
            "@name":"POP"
        },
        {
            "@count":34,
            "@name":"相信音乐"
        },
        {
            "@count":24,
            "@name":"内地"
        },
        {
            "@count":23,
            "@name":"未來的情人"
        },
        {
            "@count":20,
            "@name":"女声"
        }
    ],
    "title":{
        "$t":"未來的情人"
    },
    "author":[
        {
            "name":{
                "$t":"丁当"
            }
        },
        {
            "name":{
                "$t":"丁噹"
            }
        }
    ],
    "summary":{
        "$t":"年度横扫三大KTV亚军！\n三个来电答铃就有一个是丁当的情歌！\nK歌女王全新降临屏气凝神温暖动人\n不悲伤的单身想回温的恋人\n在遇见我的Soul mate之前\n我的灵魂保留一半有丁当相伴\n微博脸书最热烈话题情歌\nDella 丁当\n未来的情人Soul Mate\n特别收录:线上游戏阿洛斯代言与广告主题曲[冷血动物]\n首批加赠全彩挂历特典<预见Soul mate秘密相册>\n钟成虎五月天怪兽、石头小甜甜布兰妮制作人英国舞曲天王Pete Martin\n严爵 MP魔幻力量廷廷新浪摇滚乐团MOJO共创丁当情歌盛事\n灵魂抒情、摇滚庞克、英伦Dance三大风格新体验\n10首感情投射 灵魂紧紧相伴"
    },
    "link":[
        {
            "@rel":"self",
            "@href":"http:\/\/api.douban.com\/music\/subject\/5907410"
        },
        {
            "@rel":"alternate",
            "@href":"http:\/\/music.douban.com\/subject\/5907410\/"
        },
        {
            "@rel":"image",
            "@href":"http:\/\/img3.douban.com\/spic\/s4609466.jpg"
        }
    ],
    "db:attribute":[
        {
            "$t":"1",
            "@name":"discs"
        },
        {
            "$t":"专辑",
            "@name":"version"
        },
        {
            "$t":"4712758992426",
            "@name":"ean"
        },
        {
            "$t":"01.冷血动物\n02.一半\n03.未来的情人\n04.最後一次寂寞\n05.多爱少怪\n06.踹来共\n07.想原谅\n08.很爱过\n09.Symphony\n10.梦交响\n11.Back Up",
            "@name":"tracks"
        },
        {
            "$t":"2011-01-21",
            "@name":"pubdate"
        },
        {
            "$t":"未來的情人",
            "@name":"title"
        },
        {
            "$t":"丁当",
            "@name":"singer"
        },
        {
            "$t":"丁噹",
            "@name":"singer"
        },
        {
            "$t":"相信音乐",
            "@name":"publisher"
        },
        {
            "$t":"CD",
            "@name":"media"
        },
        {
            "$t":"Soul Mate",
            "@name":"aka"
        }
    ],
    "id":{
        "$t":"http:\/\/api.douban.com\/music\/subject\/5907410"
    },
    "gd:rating":{
        "@min":0,
        "@numRaters":1045,
        "@average":"7.4",
        "@max":10
    }
};